Add activesocket API.
ygrek/ocurl pull request #42
Opened 2021-05-20 13:07 UTC by toots

This PR adds the active socket API, which deprecates and replaces the last socket API: https://curl.se/libcurl/c/CURLINFO_ACTIVESOCKET.html

I haven't included the autoconf/automake changes since I am not sure how you usually re-generates those.

2021-05-20 19:17 UTC, ygrek requested changes
autoreconf should generate necessary configure changes that can be committed

2021-05-20 19:17 UTC, ygrek commented on curl.ml
> +  | CURLINFO_Socket s -> Some s
lets not break compatibility, new code will use activesocket with proper type

2021-05-20 23:03 UTC, toots commented
Sounds good. I've pushed what should be the final PR. I also fixed the `omulti` example & removed `Libevent` to avoid external dependencies so it can be built by default.

2021-05-24 16:31 UTC, ygrek commented
> I also fixed the omulti example & removed Libevent to avoid external dependencies so it can be built by default.

I appreciate the change but I cannot appreciate that it also includes the reformatting of the whole file so it is impossible to review the essential change

2021-05-24 16:36 UTC, ygrek commented
actually thanks it is in separate commit

2021-05-24 16:47 UTC, ygrek requested changes
also I want to keep libevent example, because in one form or another it is a guidance for those who want to get high performance. Maybe should use conditional compilation, but this is separate change.

2021-05-24 16:47 UTC, ygrek commented on examples/omulti.ml
> +  let th = Thread.create process () in
thread is not needed?

2021-05-24 16:47 UTC, ygrek commented on examples/omulti.ml
> +  let th = Thread.create process () in
and all the mutexes either? all the callbacks are invoked in the context of select, so it is always same thread, there is no concurrent code running

2021-05-24 16:47 UTC, ygrek commented on examples/omulti.ml
> +  let th = Thread.create process () in
actually only now I understand that adding this thread stuff is the only essential change in omulti.ml? Please don't change formatting.

2021-05-24 16:52 UTC, ygrek commented
Cherry-picked without omulti changes : bc339867711abcbe8b83f51cf27d254eab5616be
Thanks!

2021-05-24 16:52 UTC, closed without merging